# Generated by Django 4.2.7 on 2023-12-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecordE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300, null=True)),
                ('cash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300, null=True)),
                ('cash', models.IntegerField()),
                ('categoryR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.categoryr')),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryE',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='recorde',
            name='categoryE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.categorye'),
        ),
    ]
