# Generated by Django 4.2.6 on 2023-12-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_regist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regist',
        ),
    ]
