# Generated by Django 4.2.6 on 2023-12-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_delete_regist'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=50)),
                ('cEmail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
