# Generated by Django 4.2.6 on 2023-12-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_login_1_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300, null=True)),
                ('categoryE', models.CharField(max_length=50)),
                ('cash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record_R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300, null=True)),
                ('categoryR', models.CharField(max_length=50)),
                ('cash', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recordr',
            name='categoryR',
        ),
        migrations.DeleteModel(
            name='RecordE',
        ),
        migrations.DeleteModel(
            name='RecordR',
        ),
    ]
