# Generated by Django 4.2.6 on 2023-12-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_record_r1_delete_record_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_E1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300, null=True)),
                ('categoryE', models.CharField(max_length=50)),
                ('cash', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.login_1')),
            ],
        ),
        migrations.DeleteModel(
            name='Record_E',
        ),
    ]
