# Generated by Django 4.2.6 on 2023-12-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_record_e1_delete_record_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_e1',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.login_1'),
        ),
        migrations.AlterField(
            model_name='record_r1',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.login_1'),
        ),
    ]
