# Generated by Django 4.2.6 on 2023-12-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_record_e1_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_r1',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
