# Generated by Django 4.2.6 on 2023-12-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_depositgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositgoal',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='depositgoal',
            name='goal_amount',
            field=models.IntegerField(max_length=10),
        ),
    ]
