# Generated by Django 4.2.6 on 2023-12-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_remove_depositgoal_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositgoal',
            name='goal_amount',
            field=models.IntegerField(default=0),
        ),
    ]
